### ISSUE TITLE
ict2 Reverse image citation lookup not working

### ISSUE THREAD

**Issue by zachsowerby** [cite-architecture/ict2#16]
It appears that when pasting an image citation into the URN bar, the result will only return with the larger picture; for example, if one were to wish to examine a scholion, pasting "urn:cite2:hmt:vaimg.2017a:VA321RN_0491@0.6000,0.4216,0.1927,0.07275" into the URN bar would return with only with the image of 321 recto, and not the scholion located at the coordinates listed after the "@".

Thanks!

**Comment by MGelein** [comment]
This has now been fixed in the development version. You can enter one Scholion URN into the "Change Image" field. This should be implemented on the next update of the website.

For now, if you want to distribute multiple scholia you can use the URL parameters e.g.:

This URL links to two selected regions: [http://www.homermultitext.org/ict2/?urn=urn:cite2:hmt:vaimg.2017a:VA012RN_0013@0.3436,0.3931,0.03856,0.02308&urn=urn:cite2:hmt:vaimg.2017a:VA012RN_0013@0.4376,0.4371,0.03856,0.04573](http://www.homermultitext.org/ict2/?urn=urn:cite2:hmt:vaimg.2017a:VA012RN_0013@0.3436,0.3931,0.03856,0.02308&urn=urn:cite2:hmt:vaimg.2017a:VA012RN_0013@0.4376,0.4371,0.03856,0.04573)

This URL only links to one selected region: [http://www.homermultitext.org/ict2/?urn=urn:cite2:hmt:vaimg.2017a:VA012RN_0013@0.3436,0.3931,0.03856,0.02308@0.3436,0.3931,0.03856,0.02308](http://www.homermultitext.org/ict2/?urn=urn:cite2:hmt:vaimg.2017a:VA012RN_0013@0.3436,0.3931,0.03856,0.02308@0.3436,0.3931,0.03856,0.02308)
